URL_SERVICE = "https://026fa77d-af84-4fe1-bf71-0d1d6fcda730.serverhub.praktikum-services.ru"
DOC_PATH = "/docs/"
CREATE_USER_PATH = "/api/v1/users"
USERS_TABLE_PATH = "/api/db/resources/user_model.csv"
CREATE_PRODUCTS_KITS_PATH = "/api/v1/kits"